channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - keras ~= 3.4.0
  - numpy ~= 1.26
  - matplotlib
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-xdist
  - python >= 3.10, < 3.12
  - ruff
  - seaborn
  - scikit-learn
  - scipy
  - tqdm
  - tox
